In [18]:
import numpy as np
def add_vectors(u, v):
   u = np.array([1, 0])
   v = np.array([1, 1])
   print(u+v)
   u = np.array([1, 2])
   v = np.array([1, 4])
   print(u+v)
   u = np.array([1, 2, 1])
   v = np.array([1, 4, 3])
   print(u+v) 
   u = np.array([11, 0, -4, 5])
   v = np.array([2, -4, 17, 0])
   print(u+v) 
    
    
    
add_vectors([1, 0], [1, 1])

[2 1]
[2 6]
[2 6 4]
[13 -4 13  5]


In [21]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
print(a+b)
print(a)
print(b)

[2 3 4]
[1 2 3]
[1 1 1]


In [26]:
a = [1, 2, 3]
b = [1, 1, 1]
a[0] += b[0]
a[1] += b[1]
a[2] += b[2]
a

[2, 3, 4]

In [32]:
def scalar_mult(s, v):
    s =np.array([5])
    v =np.array([1,2])
    print(s*v)
    return s*v
scalar_mult(7, [3, 0, 5, 11, 2])
scalar_mult(4, [1, 2, 3])

scalar_mult(5, [1, 2])

[ 5 10]
[ 5 10]
[ 5 10]


array([ 5, 10])

In [37]:
def dot_product(u, v):
    return np.dot(u,v)

dot_product([1, 1], [1, 1])   
dot_product([1, 2], [1, 4])
dot_product([1, 2, 1], [1, 4, 3])
dot_product([2, 0, -1, 1], [1, 5, 2, 0])
            

0

In [41]:
def copy_matrix(matrix):

    copy_matrix([[1, 2], [3, 4]])
      
    copy_matrix([[1, 2, 3], [4, 5, 6]])
      
    copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
    

    copyofm = copy_matrix(m)
    copyofm
      
    for row_num, row in enumerate(copyofm):
        for col_num, col_val in enumerate(row):
           copyofm[row_num][col_num] = 42
    


In [52]:
def scalar_mult(s, m):
    a = np.dot(s,m)
    print(3*a)
scalar_mult([1, 2], [3, 4])
          

33
